### ISSUE TITLE
Implement Proper Error Handling

### ISSUE THREAD

**Issue by indiv0** [uiri/SEGIMAP#15]
Per the discussion in #3, simply using `unwrap()` on all `Result`s and `Option`s isn't good practice or very sustainable, in terms of code-debt.

Currently, our preferred error-handling system is to use our own `Error` struct by using `match` statements to manually unwrap values and wrap external errors in our custom `Error` type.

This results in overly verbose statements and (occaisionally) repeated code for error wrapping.

We can reduce the necessity of said unwrappings by replacing them with the `try!` macro.
This can be done by implementing the `FromError` trait for our custom error type.

Additonally, per the [error docs](https://doc.rust-lang.org/std/error/index.html), error messages should be handled by the `Display` trait.

As such, it is probably best to remove the `desc` field from our `Error` struct and handle error messages via an implementation of the `Display` trait.

However, in that scenario, our `Error` struct is then only a custom implementation of the standard `Error` trait described in the the [error chaining RFC](https://github.com/rust-lang/rfcs/blob/master/text/0201-error-chaining.md) and later expanded upon in the error documentation above.
Taking this into consideration, it's probably best to replace our `Error` struct with an `Error` enum (as seen in libraries such as [rustc-serialize](https://github.com/rust-lang/rustc-serialize/blob/master/src/json.rs)).

This is in our best interest because it removes the redundant and unnecessary `Error` struct, allows for easier error message handling (by simply adding a `string::String` parameter to the enum values which require it), and for simpler internal error representation and generation.
# Tasks
- [x] Replace all instances of `unwrap` in the code
- [x] Implement `FromError` for error types used in conjunction with the `try!` macro
- [x] Use `try!` macro where possible to avoid verbose match trees
- [x] Replace `Error` struct with the `ErrorKind` enum

**Comment by indiv0** [comment]
Work on this issue is being done on the [error_handling](https://github.com/uiri/SEGIMAP/tree/error_handling) branch.

**Comment by indiv0** [comment]
Silly Github, I said "**not** close #15".

**Comment by uiri** [comment]
Closed by #24
